{% set name = "pymoodef" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymoodef-{{ version }}.tar.gz
  sha256: 955ec919d5f12a3902140743a23b0d1b9670b4949cf89d08b0c16f0a182dd2b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9
    - pandas >=2.2.2
    - openpyxl >=3.1.2
    - pillow >=10.3.0

test:
  imports:
    - pymoodef
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pymoodef/
  summary: Quiz generation for Moodle in XML.
  dev_url: https://github.com/josesamos/pymoodef
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josesamos
